"""Convert a PNG (with alpha) to an RGB565 C array for the gate screen (firmware/shelf_esp32/src/logo.h).

The alpha channel is pre-blended against the screen background colour, so the image can be blitted straight
into the framebuffer with no per-pixel blending on the ESP32. Pixels that are fully transparent are written
as a key colour (LOGO_KEY) and skipped with draw16bitRGBBitmapWithTranColor, so the rounded corners of the
icon stay see-through over the gradient.

Run from the repo root (Windows):
    .venv\Scripts\python.exe tools\png_to_rgb565.py
    .venv\Scripts\python.exe tools\png_to_rgb565.py --src web\assets\icon-192.png --size 64 --bg 0b0d12
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SRC = ROOT / "web" / "assets" / "icon-192.png"
DEFAULT_OUT = ROOT / "firmware" / "shelf_esp32" / "src" / "logo.h"
KEY = 0xF81F  # pure magenta: never produced by blending the logo against a dark background


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert(src: Path, out: Path, size: int, bg: tuple[int, int, int], name: str) -> None:
    img = Image.open(src).convert("RGBA").resize((size, size), Image.LANCZOS)
    words: list[int] = []
    for y in range(size):
        for x in range(size):
            r, g, b, a = img.getpixel((x, y))
            if a == 0:
                words.append(KEY)
                continue
            t = a / 255.0
            r = round(r * t + bg[0] * (1 - t))
            g = round(g * t + bg[1] * (1 - t))
            b = round(b * t + bg[2] * (1 - t))
            c = rgb565(r, g, b)
            if c == KEY:  # astronomically unlikely, but never emit the key for a visible pixel
                c = 0xF81E
            words.append(c)
    lines = [
        "// Generated by tools/png_to_rgb565.py. Do not edit by hand.",
        f"// Source: {src.relative_to(ROOT).as_posix()} resized to {size}x{size}, alpha pre-blended against "
        f"#{bg[0]:02x}{bg[1]:02x}{bg[2]:02x}.",
        "// Fully transparent pixels hold LOGO_KEY; draw with draw16bitRGBBitmapWithTranColor(..., LOGO_KEY, ...).",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define {name}_W {size}",
        f"#define {name}_H {size}",
        f"#define {name}_KEY 0x{KEY:04X}",
        "",
        f"static const uint16_t {name}[{size * size}] = {{",
    ]
    for i in range(0, len(words), 12):
        lines.append("  " + ", ".join(f"0x{w:04X}" for w in words[i : i + 12]) + ",")
    lines += ["};", ""]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}: {size}x{size}, {size * size * 2} bytes")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--src", type=Path, default=DEFAULT_SRC)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--size", type=int, default=64, help="output width and height in pixels")
    ap.add_argument("--bg", default="0b0d12", help="screen background as RRGGBB hex (colors.h C_BG)")
    ap.add_argument("--name", default="LOGO", help="C symbol name")
    a = ap.parse_args()
    bg = tuple(int(a.bg[i : i + 2], 16) for i in (0, 2, 4))
    convert(a.src, a.out, a.size, bg, a.name)  # type: ignore[arg-type]


if __name__ == "__main__":
    main()
